import { useCallback, useEffect, useRef, useState } from "react";
import { api } from "../api";
import { useAuth } from "../auth";
import { agentSocket } from "../ws";

interface Conversation {
  id: string;
  channel: "chat" | "email";
  status: "open" | "snoozed" | "resolved";
  subject: string | null;
  assignee_id: string | null;
  last_seq: number;
  message_count: number;
  last_message_at: string | null;
  snoozed_until: string | null;
  contact_name: string | null;
  contact_email: string | null;
  contact_visitor_id: string | null;
}

interface Message {
  id: string;
  seq: number;
  sender_type: "contact" | "agent" | "system";
  sender_user_id: string | null;
  body: string;
  created_at: string;
}

interface AiSummary {
  conversation_id: string;
  summary: {
    what_user_wants: string;
    what_has_been_tried: string[];
    current_status: string;
    open_questions: string[];
    suggested_next_action: string;
    sentiment: "positive" | "neutral" | "frustrated" | "angry";
    confidence: number;
  };
  covered_through_seq: number;
  model: string;
  prompt_version: string;
  generator: "llm" | "extractive";
  updated_at: string;
}

function relativeTime(iso: string): string {
  const diffMs = Date.now() - new Date(iso).getTime();
  const minutes = Math.round(diffMs / 60000);
  if (minutes < 1) return "just now";
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.round(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.round(hours / 24)}d ago`;
}

const SENTIMENT_COLORS: Record<string, string> = {
  positive: "bg-green-100 text-green-700",
  neutral: "bg-gray-100 text-gray-600",
  frustrated: "bg-amber-100 text-amber-700",
  angry: "bg-red-100 text-red-700",
};

function SummaryCard({
  summary,
  lastSeq,
  onRegenerate,
}: {
  summary: AiSummary | null;
  lastSeq: number;
  onRegenerate: () => void;
}) {
  if (!summary) {
    return (
      <div className="text-sm text-gray-400 p-4 border rounded bg-white">
        No AI summary yet. Summaries appear once a conversation has a few messages.
      </div>
    );
  }
  const s = summary.summary;
  const isStale = summary.covered_through_seq < lastSeq;
  return (
    <div className="border rounded bg-white p-4 text-sm flex flex-col gap-3">
      <div className="flex items-center justify-between">
        <span className="font-medium">AI Summary</span>
        <div className="flex items-center gap-2">
          {isStale && <span className="text-[10px] uppercase bg-yellow-100 text-yellow-700 px-1.5 py-0.5 rounded">Stale</span>}
          <span className={`text-[10px] uppercase px-1.5 py-0.5 rounded ${SENTIMENT_COLORS[s.sentiment] || SENTIMENT_COLORS.neutral}`}>
            {s.sentiment}
          </span>
        </div>
      </div>

      <div>
        <div className="text-[11px] uppercase text-gray-400 mb-0.5">What the user wants</div>
        <div>{s.what_user_wants}</div>
      </div>

      {s.what_has_been_tried.length > 0 && (
        <div>
          <div className="text-[11px] uppercase text-gray-400 mb-0.5">Tried so far</div>
          <ul className="list-disc list-inside">
            {s.what_has_been_tried.map((t, i) => (
              <li key={i}>{t}</li>
            ))}
          </ul>
        </div>
      )}

      <div>
        <div className="text-[11px] uppercase text-gray-400 mb-0.5">Current status</div>
        <div>{s.current_status}</div>
      </div>

      {s.open_questions.length > 0 && (
        <div>
          <div className="text-[11px] uppercase text-gray-400 mb-0.5">Open questions</div>
          <ul className="list-disc list-inside">
            {s.open_questions.map((q, i) => (
              <li key={i}>{q}</li>
            ))}
          </ul>
        </div>
      )}

      <div>
        <div className="text-[11px] uppercase text-gray-400 mb-0.5">Suggested next action</div>
        <div>{s.suggested_next_action}</div>
      </div>

      <div className="border-t pt-2 flex items-center justify-between text-[11px] text-gray-400">
        <span>
          Generated by {summary.model} covering {summary.covered_through_seq} of {lastSeq} messages, {relativeTime(summary.updated_at)}
          {summary.generator === "extractive" && " (extractive fallback)"}
        </span>
        <button className="underline text-gray-500" onClick={onRegenerate}>
          Regenerate
        </button>
      </div>
    </div>
  );
}

function contactLabel(c: Conversation): string {
  return c.contact_name || c.contact_email || (c.contact_visitor_id ? `Visitor ${c.contact_visitor_id.slice(0, 8)}` : "Unknown");
}

function uuidv4(): string {
  return crypto.randomUUID();
}

export default function Inbox() {
  const { currentWorkspace, user } = useAuth();
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [statusFilter, setStatusFilter] = useState<string>("open");
  const [channelFilter, setChannelFilter] = useState<string>("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [summary, setSummary] = useState<AiSummary | null>(null);
  const [draft, setDraft] = useState("");
  const [remoteTyping, setRemoteTyping] = useState(false);
  const typingTimeoutRef = useRef<number | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const workspaceId = currentWorkspace?.id;

  const loadConversations = useCallback(async () => {
    if (!workspaceId) return;
    const params = new URLSearchParams();
    if (statusFilter) params.set("status", statusFilter);
    if (channelFilter) params.set("channel", channelFilter);
    const data = await api.get<{ conversations: Conversation[] }>(
      `/api/workspaces/${workspaceId}/conversations?${params.toString()}`
    );
    setConversations(data.conversations);
  }, [workspaceId, statusFilter, channelFilter]);

  useEffect(() => {
    loadConversations();
  }, [loadConversations]);

  useEffect(() => {
    agentSocket.connect();
    return () => agentSocket.close();
  }, []);

  useEffect(() => {
    return agentSocket.onFrame((frame) => {
      if (frame.type === "conversation.updated") {
        setConversations((prev) => {
          const updated: Conversation = frame.data.conversation;
          const idx = prev.findIndex((c) => c.id === updated.id);
          if (idx === -1) return [updated, ...prev];
          const next = [...prev];
          next[idx] = { ...next[idx], ...updated };
          return next.sort((a, b) => (b.last_message_at || "").localeCompare(a.last_message_at || ""));
        });
      } else if (frame.type === "message.new") {
        const msg = frame.data.message;
        setMessages((prev) => {
          if (msg.conversation_id !== selectedId) return prev;
          if (prev.some((m) => m.id === msg.id)) return prev;
          return [...prev, msg].sort((a, b) => a.seq - b.seq);
        });
      } else if (frame.type === "typing") {
        if (frame.data.conversation_id === selectedId && frame.data.actor_type === "contact") {
          setRemoteTyping(frame.data.is_typing);
        }
      } else if (frame.type === "summary.updated") {
        if (frame.data.conversation_id === selectedId) {
          setSummary(frame.data.summary);
        }
      }
    });
  }, [selectedId]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const openConversation = useCallback(
    async (id: string) => {
      if (!workspaceId) return;
      setSelectedId(id);
      setRemoteTyping(false);
      setSummary(null);
      const data = await api.get<{ conversation: Conversation; messages: Message[]; summary: AiSummary | null }>(
        `/api/workspaces/${workspaceId}/conversations/${id}`
      );
      setMessages(data.messages);
      setSummary(data.summary);
      agentSocket.subscribe(id);
      agentSocket.sync(id, data.messages.length ? data.messages[data.messages.length - 1].seq : 0);
      agentSocket.markRead(id, data.conversation.last_seq);
    },
    [workspaceId]
  );

  const sendMessage = useCallback(() => {
    if (!selectedId || !draft.trim()) return;
    agentSocket.sendMessage(selectedId, draft.trim(), uuidv4());
    setDraft("");
    agentSocket.typing(selectedId, false);
  }, [selectedId, draft]);

  const handleDraftChange = (value: string) => {
    setDraft(value);
    if (!selectedId) return;
    agentSocket.typing(selectedId, true);
    if (typingTimeoutRef.current) window.clearTimeout(typingTimeoutRef.current);
    typingTimeoutRef.current = window.setTimeout(() => {
      agentSocket.typing(selectedId, false);
    }, 3000);
  };

  const doAction = async (action: "assign" | "resolve" | "snooze" | "reopen") => {
    if (!workspaceId || !selectedId) return;
    if (action === "assign") {
      await api.post(`/api/workspaces/${workspaceId}/conversations/${selectedId}/assign`, { assignee_id: user?.id });
    } else if (action === "resolve") {
      await api.post(`/api/workspaces/${workspaceId}/conversations/${selectedId}/resolve`);
    } else if (action === "reopen") {
      await api.post(`/api/workspaces/${workspaceId}/conversations/${selectedId}/reopen`);
    } else if (action === "snooze") {
      const snoozedUntil = new Date(Date.now() + 60 * 60 * 1000).toISOString();
      await api.post(`/api/workspaces/${workspaceId}/conversations/${selectedId}/snooze`, { snoozed_until: snoozedUntil });
    }
    loadConversations();
  };

  const regenerateSummary = async () => {
    if (!workspaceId || !selectedId) return;
    await api.post(`/api/workspaces/${workspaceId}/conversations/${selectedId}/summary/regenerate`);
  };

  const selected = conversations.find((c) => c.id === selectedId) || null;

  return (
    <div className="h-full flex">
      <div className="w-80 border-r bg-white flex flex-col">
        <div className="p-3 border-b flex flex-col gap-2">
          <div className="font-medium">Inbox</div>
          <div className="flex gap-2 text-xs">
            <select className="border rounded px-1 py-0.5" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}>
              <option value="">All statuses</option>
              <option value="open">Open</option>
              <option value="snoozed">Snoozed</option>
              <option value="resolved">Resolved</option>
            </select>
            <select className="border rounded px-1 py-0.5" value={channelFilter} onChange={(e) => setChannelFilter(e.target.value)}>
              <option value="">All channels</option>
              <option value="chat">Chat</option>
              <option value="email">Email</option>
            </select>
          </div>
        </div>
        <div className="flex-1 overflow-y-auto">
          {conversations.length === 0 && (
            <div className="text-sm text-gray-400 p-6 text-center">
              No conversations yet. Once a visitor messages you through the widget, or an email comes in, it
              will show up here.
            </div>
          )}
          {conversations.map((c) => (
            <button
              key={c.id}
              onClick={() => openConversation(c.id)}
              className={`w-full text-left px-3 py-3 border-b hover:bg-gray-50 ${selectedId === c.id ? "bg-gray-100" : ""}`}
            >
              <div className="flex justify-between items-center">
                <span className="font-medium text-sm">{contactLabel(c)}</span>
                <span className="text-[10px] uppercase text-gray-400">{c.channel}</span>
              </div>
              <div className="text-xs text-gray-500 truncate">{c.subject || `${c.message_count} messages`}</div>
              <div className="text-[10px] text-gray-400 mt-1">{c.status}</div>
            </button>
          ))}
        </div>
      </div>

      <div className="flex-1 flex flex-col">
        {!selected ? (
          <div className="flex-1 flex items-center justify-center text-gray-400">
            <p>Select a conversation to get started.</p>
          </div>
        ) : (
          <>
            <div className="border-b px-4 py-2 flex justify-between items-center bg-white">
              <div>
                <div className="font-medium text-sm">{contactLabel(selected)}</div>
                <div className="text-xs text-gray-400">{selected.status}</div>
              </div>
              <div className="flex gap-2 text-xs">
                <button className="border rounded px-2 py-1" onClick={() => doAction("assign")}>
                  Assign to me
                </button>
                <button className="border rounded px-2 py-1" onClick={() => doAction("snooze")}>
                  Snooze 1h
                </button>
                {selected.status === "resolved" ? (
                  <button className="border rounded px-2 py-1" onClick={() => doAction("reopen")}>
                    Reopen
                  </button>
                ) : (
                  <button className="border rounded px-2 py-1" onClick={() => doAction("resolve")}>
                    Resolve
                  </button>
                )}
              </div>
            </div>
            <div className="flex-1 overflow-y-auto p-4 bg-gray-50">
              {messages.map((m) => (
                <div key={m.id} className={`mb-3 flex ${m.sender_type === "agent" ? "justify-end" : "justify-start"}`}>
                  <div
                    className={`max-w-[70%] px-3 py-2 rounded-lg text-sm whitespace-pre-wrap break-words ${
                      m.sender_type === "agent" ? "bg-gray-900 text-white" : "bg-white border"
                    }`}
                  >
                    {m.body}
                  </div>
                </div>
              ))}
              <div ref={messagesEndRef} />
            </div>
            <div className="h-5 px-4 text-xs text-gray-400">{remoteTyping ? "Visitor is typing..." : ""}</div>
            <div className="border-t p-3 flex gap-2 bg-white">
              <textarea
                className="flex-1 border rounded px-2 py-1 text-sm resize-none h-10"
                value={draft}
                maxLength={10000}
                onChange={(e) => handleDraftChange(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    sendMessage();
                  }
                }}
                placeholder="Type a reply..."
              />
              <button className="bg-gray-900 text-white rounded px-4 text-sm" onClick={sendMessage}>
                Send
              </button>
            </div>
          </>
        )}
      </div>

      {selected && (
        <div className="w-80 border-l bg-gray-50 p-3 overflow-y-auto flex flex-col gap-3">
          <div>
            <div className="text-[11px] uppercase text-gray-400 mb-1">Contact</div>
            <div className="bg-white border rounded p-3 text-sm">
              <div className="font-medium">{contactLabel(selected)}</div>
              {selected.contact_email && <div className="text-gray-500 text-xs mt-0.5">{selected.contact_email}</div>}
            </div>
          </div>
          <div>
            <div className="text-[11px] uppercase text-gray-400 mb-1">AI Summary</div>
            <SummaryCard summary={summary} lastSeq={selected.last_seq} onRegenerate={regenerateSummary} />
          </div>
        </div>
      )}
    </div>
  );
}
